package com.jarvisdev.generator;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

public class ProjectGenerator {

    public void generate(ProjectTemplate template) {

        String projectName = template.getProjectName();

        File projectFolder = new File(projectName);

        if (!projectFolder.exists()) {
            projectFolder.mkdir();
        }

        File srcFolder = new File(projectFolder, "src");
        srcFolder.mkdir();

        createReadme(projectFolder, projectName);

        createMainJava(srcFolder);

        createPom(projectFolder);

        createGitIgnore(projectFolder);

        System.out.println("✅ Project Generated Successfully");
        System.out.println("📁 " + projectFolder.getAbsolutePath());
    }

    private void createReadme(File projectFolder,
                              String projectName) {

        try {

            File readme =
                    new File(projectFolder, "README.md");

            FileWriter writer =
                    new FileWriter(readme);

            writer.write("# " + projectName + "\n");
            writer.write("Generated by JarvisDev AI");

            writer.close();

        } catch (IOException e) {

            System.out.println(
                    "Error creating README: "
                            + e.getMessage()
            );
        }
    }

    private void createMainJava(File srcFolder) {

        try {

            File mainFile =
                    new File(srcFolder, "Main.java");

            FileWriter writer =
                    new FileWriter(mainFile);

            writer.write("""
public class Main {

    public static void main(String[] args) {

        System.out.println("Hello from JarvisDev");
    }
}
""");

            writer.close();

        } catch (IOException e) {

            e.printStackTrace();
        }
    }

    private void createPom(File projectFolder) {

        try {

            File pom =
                    new File(projectFolder, "pom.xml");

            FileWriter writer =
                    new FileWriter(pom);

            writer.write("""
<project>
    <modelVersion>4.0.0</modelVersion>
</project>
""");

            writer.close();

        } catch (IOException e) {

            e.printStackTrace();
        }
    }

    private void createGitIgnore(File projectFolder) {

        try {

            File gitignore =
                    new File(projectFolder, ".gitignore");

            FileWriter writer =
                    new FileWriter(gitignore);

            writer.write("""
target/
.idea/
*.iml
""");

            writer.close();

        } catch (IOException e) {

            e.printStackTrace();
        }
    }
}