package com.jarvisdev.generator;

import com.jarvisdev.generator.templates.ConsoleTemplate;
import com.jarvisdev.generator.templates.SpringBootTemplate;
import com.jarvisdev.generator.templates.WebTemplate;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;

public class ProjectGenerator {

    public void generate(ProjectTemplate template) {

        String projectName = template.getProjectName();
        String projectType = template.getProjectType();

        File projectFolder = new File(projectName);

        if (!projectFolder.exists()) {
            projectFolder.mkdir();
        }

        // Create project structure based on type
        if (projectType.equals("console")) {

            new ConsoleTemplate()
                    .create(projectFolder);

        } else if (projectType.equals("web")) {

            new WebTemplate()
                    .create(projectFolder);

        } else if (projectType.equals("spring")) {

            new SpringBootTemplate()
                    .create(projectFolder);
        }

        createReadme(projectFolder, projectName);

        createPom(projectFolder);

        createGitIgnore(projectFolder);

        System.out.println();
        System.out.println("Project Type : " + projectType);
        System.out.println("✅ Project Generated Successfully");
        System.out.println("📁 " + projectFolder.getAbsolutePath());
    }

    private void createReadme(File projectFolder,
                              String projectName) {

        try {

            File readme =
                    new File(projectFolder, "README.md");

            FileWriter writer =
                    new FileWriter(readme);

            writer.write("# " + projectName + "\n\n");
            writer.write("Generated by JarvisDev AI");

            writer.close();

        } catch (IOException e) {

            System.out.println(
                    "Error creating README: "
                            + e.getMessage()
            );
        }
    }

    private void createPom(File projectFolder) {

        try {

            File pom =
                    new File(projectFolder, "pom.xml");

            FileWriter writer =
                    new FileWriter(pom);

            writer.write("""
                    <project>
                        <modelVersion>4.0.0</modelVersion>
                    </project>
                    """);

            writer.close();

        } catch (IOException e) {

            System.out.println(
                    "Error creating pom.xml: "
                            + e.getMessage()
            );
        }
    }

    private void createGitIgnore(File projectFolder) {

        try {

            File gitignore =
                    new File(projectFolder, ".gitignore");

            FileWriter writer =
                    new FileWriter(gitignore);

            writer.write("""
                    target/
                    .idea/
                    *.iml
                    """);

            writer.close();

        } catch (IOException e) {

            System.out.println(
                    "Error creating .gitignore: "
                            + e.getMessage()
            );
        }
    }
}